### ISSUE TITLE
Plain black screen

### ISSUE THREAD

**Issue by drampelt** [unconed/TermKit#27]
I have nodekit running in the background but when I run termkit all I see is a black screen with absolutely nothing on it.
Screenshot: http://cl.ly/6sJG

**Comment by hmottestad** [comment]
Your firewall may be blocking the node.js server.

**Comment by imeyer** [comment]
I had this same issue. Running

`npm install mime`

in the `TermKit/Node` directory fixed it.

This assumes that you are running `node node kit.js`

**Comment by mculp** [comment]
Check your `node nodekit.js` output. It should print a stacktrace. Probably missing the mime package.

**Comment by drampelt** [comment]
Fixed, it was the nodekit.js not having mime even though I installed. Reinstalling node/npm/mime fixed it.

**Comment by tovbinm** [comment]
Still have a black screen:

matthew@Photon:Node$ node ./nodekit.js 
   info  - socket.io started
   debug - client authorized
   info  - handshake authorized
   info  - handshaken 30758d5305378354f5cf58eda0f77a76
   debug - setting request GET /socket.io/1/websocket/30758d5305378354f5cf58eda0f77a76
   debug - publishing that 30758d5305378354f5cf58eda0f77a76 connected
   debug - initializing client store for 30758d5305378354f5cf58eda0f77a76
   debug - set heartbeat interval for client 30758d5305378354f5cf58eda0f77a76
   debug - subscribing 30758d5305378354f5cf58eda0f77a76
   debug - websocket writing 1::
   debug - websocket writing 4:::{"termkit":"1","timestamp":1311366740444}
   debug - websocket received data packet 3:::[object Object]
   debug - got packet
   debug - websocket received data packet 3:::[object Object]
   debug - got packet

**Comment by surjikal** [comment]
Same here.

**Comment by mariorodriguespt** [comment]
+1

**Comment by manikantag** [comment]
same here. 

```
info  - socket.io started
debug - served static content /socket.io.js
debug - client authorized
info  - handshake authorized s3k1vpX5rom9zYZu0U-E
debug - setting request GET /socket.io/1/websocket/s3k1vpX5rom9zYZu0U-E
debug - set heartbeat interval for client s3k1vpX5rom9zYZu0U-E
debug - client authorized for
debug - websocket writing 1::
debug - websocket writing 3:::[object Object]
debug - emitting heartbeat for client s3k1vpX5rom9zYZu0U-E
debug - websocket writing 2::
debug - set heartbeat timeout for client s3k1vpX5rom9zYZu0U-E
debug - got heartbeat packet
debug - cleared heartbeat timeout for client s3k1vpX5rom9zYZu0U-E
debug - set heartbeat interval for client s3k1vpX5rom9zYZu0U-E
```

I've installed 'mime' and I can see TermKit\Node\node_modules\mime

Environment: Windows 7, nodejs 0.8.4, connect 2.4.2, mime 1.2.7, socket.io 0.9.8

Please help to fix. Thanks
